# Generated by Django 4.0.6 on 2022-08-04 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_sent',),
            },
        ),
        migrations.CreateModel(
            name='ItemReciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.itemsender')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('weight', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='package_photos')),
                ('paid', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('transit', 'ON TRANSIT'), ('withheld', 'WITHHELD'), ('sent', 'SENT'), ('delivered', 'DELIVERED')], default='transit', max_length=15)),
                ('problem_type', models.CharField(choices=[('no problem', 'No Problems'), ('paperwork', 'PAPERWORK_OVERLOAD'), ('custom clerance', 'CUSTOM CLEARANCE'), ('bad weather', 'BAD WEATHER'), ('holidays', 'HOLYDAYS')], default='NO PROBLEM', max_length=15)),
                ('item_code', models.CharField(max_length=20)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_recieved', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_shipped', models.DateTimeField(default=datetime.datetime(2022, 8, 5, 14, 37, 4, 71066, tzinfo=utc))),
                ('delivery_frame', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 14, 37, 4, 71066, tzinfo=utc))),
                ('item_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.itemreciever')),
                ('item_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.itemsender')),
            ],
            options={
                'ordering': ('-date_sent', '-date_recieved'),
            },
        ),
    ]
