# Generated by Django 4.0.6 on 2022-08-05 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetail',
            old_name='name',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='itemsender',
            name='fullname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 11, 12, 39, 235262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 11, 12, 39, 235262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemreciever',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='itemsender',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='itemsender',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
