# Generated by Django 4.0.6 on 2022-08-08 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_rename_name_itemdetail_item_name_itemsender_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsender',
            old_name='fullname',
            new_name='sender_fullname',
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 19, 55, 19, 912896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 19, 55, 19, 912896, tzinfo=utc)),
        ),
    ]
