# Generated by Django 4.0.6 on 2022-08-08 20:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipment', '0003_rename_fullname_itemsender_sender_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsender',
            old_name='sender_fullname',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 20, 9, 47, 602409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 20, 9, 47, 602409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='item_reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_receiver', to='shipment.itemreciever'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='item_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sender', to='shipment.itemsender'),
        ),
        migrations.AlterField(
            model_name='itemreciever',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shipment.itemsender'),
        ),
        migrations.AlterField(
            model_name='itemsender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
