# Generated by Django 4.0.6 on 2022-08-08 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_rename_sender_fullname_itemsender_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 20, 22, 32, 592787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 20, 22, 32, 592787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemreciever',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_to_receiver', to='shipment.itemsender'),
        ),
    ]
