# Generated by Django 4.0.6 on 2022-08-16 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_remove_itemdetail_problem_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetail',
            old_name='item_reciever',
            new_name='item_receiver',
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 18, 28, 57, 151461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 18, 28, 57, 151461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemreciever',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
