# Generated by Django 4.0.6 on 2022-08-19 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_alter_itemdetail_date_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 14, 38, 24, 258371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 14, 38, 24, 258371, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemreciever',
            name='country',
            field=django_countries.fields.CountryField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemsender',
            name='country',
            field=django_countries.fields.CountryField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
