# Generated by Django 4.1.1 on 2022-10-04 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0012_alter_itemdetail_date_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 17, 25, 7, 958506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 17, 25, 7, 958506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('en route', 'EN ROUTE'), ('withheld', 'WITHHELD'), ('sent', 'SENT'), ('delivered', 'DELIVERED')], default='transit', max_length=100),
        ),
    ]
